---
title: "Disability Overdose Death"
author: "Jackson M Luckey"
date: "2/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidycensus)
library(janitor)
library(here)
```

```{r census_functions, echo=FALSE}
# removes " County, Ohio" from county column (because it's the same in all cases)
clean_county_col<- function(df) {

  df <- df %>%
    mutate(county = str_remove(county, " County, Ohio"))

}

clean_tidycensus_table <- function(df) {

  # rename the "NAME" column to county
  df <- df %>%
    rename(county = NAME)

  df <- clean_county_col(df)

}

get_acs_tidycensus_table <- function(table, year, survey = "acs1") {

  df <- get_acs("county",
                state = "OH",
                year = year,
                table = table,
                survey = survey,
                cache = TRUE)

  df$table <- table

  df <- clean_tidycensus_table(df)

}

make_census_table_wide <- function(df) {

  df <- df %>%
    pivot_longer(cols = c(estimate, moe)) %>%
    pivot_wider(names_from = c(name, variable), values_from = value)

}
```

```{r disability_data, echo=FALSE}
# load the census data
years <- 2010:2018
for (year in years) {
  tmp <- get_acs_tidycensus_table("S1810", year, "acs1") %>%
    make_census_table_wide()
  tmp$year <- year
  if (year == 2010) {
    df <- tmp
  } else {
    df <- bind_rows(tmp, df)
  }
}
```

```{r death_data, echo=FALSE}
deaths <- read_csv(here("Data", "CSV", "OverdoseDeathsTall.csv")) %>%
  rename(county = County)
df <- left_join(df, deaths)
```

```{r disability_var_labels, echo=FALSE}
vars <- load_variables(2010, "acs1/subject", cache = TRUE) %>%
  mutate(keep = stringr::str_detect(name, "S1810")) %>%
  filter(keep == TRUE)
```

```{r geom, echo=FALSE}
geom <- get_acs("county",
                state = "OH",
                variables = "S1810_C01_001",
                geometry = TRUE,
                survey = "acs1") %>%
  clean_tidycensus_table()
```

```{r test_map, echo=FALSE}
test <- left_join(deaths, geom) %>%
  filter(!is.na(estimate)) %>%
  mutate(rateOD = (deaths / estimate) * 10000) %>%
  filter(year != 2005) # to make a nice 3x4

ggplot(test, aes(fill = rateOD, geometry = geometry)) +
  geom_sf() +
  facet_wrap(vars(year)) +
  scale_fill_viridis_c() +
  theme_minimal() +
  theme(axis.text = element_blank(),
        line = element_blank()) +
  ggtitle("Annual Opioid Overdose Deaths per 10,000 People in Ohio") +
  labs(fill = "Overdose Deaths")
```

```{r}
ggplot(df, aes(x = estimate_S1810_C01_001, y = deaths)) +
  geom_jitter() +
  scale_y_log10() +
  scale_x_log10() +
  geom_smooth(method = "lm") +
  theme_minimal() +
  labs(x = "Population", y = "Opioid Overdose Deaths") +
  ggtitle("OD Deaths and County Population")
```