---
title: "Transfer Receipts and Overdose Deaths"
author: "jacksonmluckey@gmail.com"
date: "9/20/2019"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = FALSE)

# Load the necessary packages
library(tidyverse)
library(here)

# Load the necessary datasets and rename columns as needed to enable merging them
OverdoseDeathsTall <- read_csv(here("Data", "CSV", "OverdoseDeathsTall.csv")) %>%
  mutate(Year = year,
         year = NULL) # Capitalize the Year column
TransferReceiptsTall <- read_csv(here("Data", "CSV", "TransferReceiptsTall.csv")) %>%
  mutate(County = Area,
         Area = NULL) # Rename Area to County
PopTall <- read_csv(here("Data", "CSV", "OhioCountyPopulationYearTall.csv")) %>%
  filter(Year == 2010) %>% # use most recent year available in the data
  mutate(Year = NULL) # remove year column to allow it to populate for all years

# Merge the datasets
df <- left_join(OverdoseDeathsTall, TransferReceiptsTall)
df <- left_join(df, PopTall)

# Filter years before 2012 (due to no Transfer Receipts data)
df <- df %>%
  filter(Year > 2011)

# Calculate overdose rate
df <- df %>%
  mutate(Rate = (deaths / Population) * 100000) # num dead per 100000 pop per year
```

# Transfer Receipts and Opioid Overdoses in Ohio

```{r}
ggplot(df, aes(y = PercentTotalIncome, x = Rate, size = Population)) +
  geom_point() +
  theme_classic() +
  labs(y = "Yearly Opioid Overdose Deaths per 100,000 People",
       x = "Government Transfers as Percent of Total Income",
       size = "County Population") +
  ggtitle("Government Transfers and Opioid Overdose Rate")
```

This graph does not appear to show anything meaninful